name: pageflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  file_picker: ^10.0.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  http: ^1.3.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^29.1.35
  water_drop_nav_bar: ^2.2.2
  just_audio: ^0.10.0
  audio_session: ^0.2.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/appicon.png"
  adaptive_icon_background: "#2196F3" # Optional: For Android adaptive icon
  adaptive_icon_foreground: "assets/appicon.png"
