// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK97RtvsivQRiwDddYSYXQ89u2mXl-lg4',
    appId: '1:390888525321:web:062a648d65db1cb9dd32d8',
    messagingSenderId: '390888525321',
    projectId: 'pageflow-bdba0',
    authDomain: 'pageflow-bdba0.firebaseapp.com',
    storageBucket: 'pageflow-bdba0.firebasestorage.app',
    measurementId: 'G-ETM7DVGQTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxfgGnNuv-MQH7vshTUcWJrG5j9JYX600',
    appId: '1:390888525321:android:00cf0e92d4034db7dd32d8',
    messagingSenderId: '390888525321',
    projectId: 'pageflow-bdba0',
    storageBucket: 'pageflow-bdba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVWsXCuwC0sZ726IHC9gRfQKbEN-zR80',
    appId: '1:390888525321:ios:d7b0062833ad38f1dd32d8',
    messagingSenderId: '390888525321',
    projectId: 'pageflow-bdba0',
    storageBucket: 'pageflow-bdba0.firebasestorage.app',
    iosBundleId: 'com.example.pageflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVWsXCuwC0sZ726IHC9gRfQKbEN-zR80',
    appId: '1:390888525321:ios:d7b0062833ad38f1dd32d8',
    messagingSenderId: '390888525321',
    projectId: 'pageflow-bdba0',
    storageBucket: 'pageflow-bdba0.firebasestorage.app',
    iosBundleId: 'com.example.pageflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK97RtvsivQRiwDddYSYXQ89u2mXl-lg4',
    appId: '1:390888525321:web:01b937f5aafaaa77dd32d8',
    messagingSenderId: '390888525321',
    projectId: 'pageflow-bdba0',
    authDomain: 'pageflow-bdba0.firebaseapp.com',
    storageBucket: 'pageflow-bdba0.firebasestorage.app',
    measurementId: 'G-7RYXCHJ7Z7',
  );
}
